<?php
/**
 * @file
 * Utility functions for the events site.
 */

/* --- HOOKS ---------------------------------------------------------------- */

/**
 * Implements hook_init().
 */
function poll_utility_init() {
  // Let's check if user is logged in.
  $links_array = array(
    'user/login',
  );

  if (user_is_logged_in() === false && !in_array(current_path(), $links_array)) {
    // We will redirect anon user to front page with login form.

    // @TODO: Find another way for redirect.
    drupal_goto('user/login', array(), 302);
  }
  else {
    // drupal_goto('home', array(), 302);
  }
}
